### Add Skin 1
POST http://127.0.0.1:5002/add-skin
Content-Type: application/json

{
  "name": "Dragon AK47",
  "price": 500,
  "stock": 10,
  "image": "dragon.png"
}

### Add Skin 2
POST http://127.0.0.1:5002/add-skin
Content-Type: application/json

{
  "name": "Ice M4",
  "price": 300,
  "stock": 5,
  "image": "ice.png"
}

### Get All Skins
GET http://127.0.0.1:5002/skins